In [0]:
import numpy as np

In [0]:
arr1=np.arange(20).reshape(4,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [0]:
# Q1 Write a numpy code to swap col1([0,5,10,15]) with col4([3,8,13,18])
# Hint----> Fancy Indexig
import numpy as np
arr1=np.arange(20).reshape(4,5)
arr1
aarr1[:,[0,3]]= arr1[:,[3,0]]
arr1


array([[ 3,  1,  2,  0,  4],
       [ 8,  6,  7,  5,  9],
       [13, 11, 12, 10, 14],
       [18, 16, 17, 15, 19]])

In [0]:
# Q2 Write a numpy code to reverse the rows of arr1
# The output should be [15, 16, 17, 18, 19] as first row and [ 0,  1,  2,  3,  4] as last row
import numpy as np
arr1=np.arange(20).reshape(4,5)
arr1
arr1[[0,3],:]=arr1[[3,0],:]
arr1

array([[15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

In [0]:
arr2=np.array([[1,2,np.nan],[4,5,6],[np.nan,np.nan,9]])
arr2

array([[ 1.,  2., nan],
       [ 4.,  5.,  6.],
       [nan, nan,  9.]])

In [0]:
# Q3 Write a code to replace all the nan(missing values) of arr2 with the mean of arr2
import numpy as np
arr2=np.array([[1,2,np.nan],[4,5,6],[np.nan,np.nan,9]])
arr2
me=np.nanmean(arr2)
arr2[np.isnan(arr2)]=me
arr2







array([[1. , 2. , 4.5],
       [4. , 5. , 6. ],
       [4.5, 4.5, 9. ]])

In [0]:
arr3=np.random.randint(low=1,high=100,size=20).reshape(5,4)
arr3

array([[22, 86, 19, 79],
       [54, 51, 72, 60],
       [ 7, 44, 88, 85],
       [25, 85, 33, 66],
       [19, 65, 23, 48]])

In [0]:
# Q4 Write a code which can fetch all items from arr3 which are either greater than 25 or a multiple of 3
import numpy as np
arr3=np.random.randint(low=1,high=100,size=20).reshape(5,4)
print(arr3)
arr3[(arr3>25)|(arr3%3==0)]

  

[[22  9  5 29]
 [98 78 56 43]
 [16 28  9 99]
 [83 57  4 48]
 [17 61  7 13]]


array([ 9, 29, 98, 78, 56, 43, 28,  9, 99, 83, 57, 48, 61])

In [0]:
# Q5 Write a code to find the 10th, 25th, 50th(median) percentile of arr3
# Percentiles are a very important concept in Statistics. If you don't know about it refer the video below
# https://www.youtube.com/watch?v=Snf6Wpn-L4c
# Hint: to solve this function google np.percentile()

In [0]:
import numpy as np
arr3=np.random.randint(low=1,high=100,size=20).reshape(5,4)
print(arr3)
print("10th percentile of an array: ",np.percentile(arr3,10))
print("25th percentile of an array: ",np.percentile(arr3,25))
print("50th percentile of an array: ",np.percentile(arr3,50))







[[ 6 23 57 12]
 [65 99  2 67]
 [57 59 34 19]
 [44  6 50 64]
 [29 26 43 57]]
10th percentile of an array:  6.0
25th percentile of an array:  22.0
50th percentile of an array:  43.5
